spring:
  profiles:
    active: dev
  application:
    name: static_resource_server
server:
  port: 7774
logging:
  config: classpath:logback-spring.xml
  path: ./logs


---
spring:
  profiles: dev
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
#    # 连接超时时间（毫秒）
    timeout: 2000
    jedis:
#    lettuce:
      pool:
#      # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
#        # 连接池中的最大空闲连接
        max-idle: 8
#        # 连接池中的最小空闲连接
        min-idle: 0



---
spring:
  profiles: jicheng
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    timeout: 0
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 8
        min-idle: 0

---
spring:
  profiles: pro
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    timeout: 0
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 8
        min-idle: 0
