spring:
  profiles:
    active: dev
  application:
    name: static_resource_server
server:
  port: 7774
logging:
  config: classpath:logback-spring.xml
  path: ./logs
request_http_type: https
#配置不走缓存的host
static_resource_not_cache_hosts:
#库存服务地址
dodoca_php_stock_interface: http://172.17.2.211:9401/router/rest?site=tester&callerid=tester&uuid=tester_%s&method=service.stock.get&goods_ids[]=%s
#key过期时间 s
dodoca_redis_key_expire_time: 300
dodoca_log_level: 0
dodoca_rest_read_timeout: 60000
dodoca_rest_connection_timeout: 60000

dodoca_rest_stock_read_timeout: 20000
dodoca_rest_stock_connection_timeout: 20000


---
spring:
  profiles: dev
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
#    数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    timeout: 500
    jedis:
#    lettuce:
      pool:
#      # 连接池最大连接数（使用负值表示没有限制）
        max-active: 300
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1s
#        # 连接池中的最大空闲连接
        max-idle: 8
#        # 连接池中的最小空闲连接
        min-idle: 0





---
spring:
  profiles: jicheng
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    timeout: 500
    jedis:
      pool:
        max-active: 300
        max-wait: -1s
        max-idle: 8
        min-idle: 0

---
spring:
  profiles: pro
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    timeout: 500
    jedis:
      pool:
        max-active: 300
        max-wait: -1s
        max-idle: 8
        min-idle: 0
